proxy:
  title: cartoGRAPHs
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8050
  authentication: none
  admin-groups: scientists
  container-wait-time: 60000
  # Example: 'simple' authentication configuration
  users:
  - name: chris
    password: mila
    groups: scientists
  - name: jeff
    password: password
    groups: mathematicians
  # Example: 'ldap' authentication configuration
  ldap:
    url: ldap://ldap.forumsys.com:389/dc=example,dc=com
    user-dn-pattern: uid={0}
    group-search-base:
    group-search-filter: (uniqueMember={0})
    manager-dn: cn=read-only-admin,dc=example,dc=com
    manager-password: password
  # Docker configuration
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: cartoGRAPHs
    display-name: cartoGRAPHs
    description: A framework for interpretable network visualizations
    #    container-cmd: ["R", "-e", "shiny::runApp('/root/Explorer')"]
    port: 8050
    container-image: carto:20210609
    access-groups: [scientists, mathematicians]

logging:
  file:
    name: shinyproxy.log
